# Minimal theme for Hugo - Zero JavaScript
name = "Minimal"
license = "MIT"
licenselink = "https://github.com/pelauimagineering"
description = "A minimal Hugo theme with zero JavaScript"

[author]
  name = "Pelau"

[original]
  name = "Minimal"
  homepage = "https://write.pelau.com"
